version: '3.8'

services:
  lifyo:
    build: .
    image: lifyo-server
    container_name: lifyo-server
    ports:
      - "28000:28000"
      - "28001:28001"
      - "28002:28002"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/server:/home/lifuser/yoserver
    environment:
      - DB_USER=lif_1
      - DB_PASS=supersafepassword
    restart: unless-stopped
